### PR TITLE
*: Add checks for chart version updates and changelog

### PR DESCRIPTION
**Pull request by matej-g**
# Description

This change adds GitHub actions workflow for checks on PRs:
- For chart version update, if changes to chart-related to files are being made
- For changelog update, if changes to a particular component are being made.

The workflow config is a bit more verbose, because we need to check path for each chart / component, but this was the only workable approach for me.

Part of #216.

# How Has This Been Tested?

Will be tested on a draft PR once this is merged (not sure if possible to test before merge)

# Checklist:
- [ ] I have updated the relevant Helm chart(s) version(s)
- [ ] I have updated the relevant component changelog(s)
- [X] This change does not affect any particular component (e.g. it's CI or docs change)

### CODE REVIEW

**Comment by ArthurSens** [comment]
> Will be tested on a draft PR once this is merged (not sure if possible to test before merge)

I guess you could make changes to a particular chart, commit and see if the check fails in CI. If it does, we can just drop the last commit and merge afterwards?

**Comment by nicolastakashi** [comment]
This looks amazing 🥳

**Comment by matej-g** [comment]
Good idea @ArthurSens, I'll turn this into draft and test it

**Comment by matej-g** [comment]
Sorry for the delay and noise, took me a bit to figure out how to properly detect file changes. All should work now, here is an example action run when I added a test change: https://github.com/coralogix/telemetry-shippers/actions/runs/5043809228/jobs/9046070677#step:8:11

Please review @nicolastakashi @ArthurSens 🙇

**Review by nicolastakashi — APPROVED** [review]

**Pull request merged**
