### PR TITLE
Update values.yaml

### PR DESCRIPTION
**Pull request by sergeylanzman**
Current configuration try to create pod fluentbit for each node of fargate and it’s not working

### CODE REVIEW

**Review by avivgold098 — COMMENTED** [review]
@sergeylanzman hey sergey, thank you for involving in the project.

Can you elaborate more on the use case? As this intend from helm installation on k8s

**Comment by sergeylanzman** [comment]
I installed this helm chart with default values on EKS cluster with fargate pods. Every fargate pods look in Kubernetes as node, so with default settings, I got one pending fluentbit pod for each fargate pod. Because it's daemonset

**Comment by nicolastakashi** [comment]
Hi @sergeylanzman is this still an issue or we can close this?

**Comment by nicolastakashi** [comment]
I'm closing this since we don't have any activity, if needed please reopen the PR 😄

**Pull request closed without merging**
